/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as ApiPublicMediaSplatRouteImport } from './routes/api/public/media/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMediaSplatRoute = ApiPublicMediaSplatRouteImport.update({
  id: '/api/public/media/$',
  path: '/api/public/media/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/projects/$slug': typeof ProjectsSlugRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/api/public/media/$': typeof ApiPublicMediaSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/projects/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/media/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/projects/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/media/$'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/projects/$slug'
    | '/api/public/sitemap.xml'
    | '/api/public/media/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ProjectsSlugRoute: typeof ProjectsSlugRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicMediaSplatRoute: typeof ApiPublicMediaSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/media/$': {
      id: '/api/public/media/$'
      path: '/api/public/media/$'
      fullPath: '/api/public/media/$'
      preLoaderRoute: typeof ApiPublicMediaSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ProjectsSlugRoute: ProjectsSlugRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicMediaSplatRoute: ApiPublicMediaSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
